INSERT INTO word_pairs values (25, 'bonheur','amour');
INSERT INTO word_pairs values (26, 'guepe','abeille');
INSERT INTO word_pairs values (27, 'politique','histoire');
INSERT INTO word_pairs values (28, 'tennis','badminton');
INSERT INTO word_pairs values (29, 'gorille','orang-outan');
INSERT INTO word_pairs values (30, 'oeil','camera');
INSERT INTO word_pairs values (31, 'piment','wasabi');
INSERT INTO word_pairs values (32, 'dauphin','baleine');
INSERT INTO word_pairs values (33, 'snapchat','whatsapp');
INSERT INTO word_pairs values (34, 'gel douche','shampooing');
INSERT INTO word_pairs values (35, 'violon','guitare');
INSERT INTO word_pairs values (36, 'rhinoceros','buffle');
INSERT INTO word_pairs values (37, 'fanta','coca cola');
INSERT INTO word_pairs values (38, 'camping','pique-nique');
INSERT INTO word_pairs values (39, 'sac a dos','sac a main');
INSERT INTO word_pairs values (40, 'le seigneur des anneaux','le hobbit');
INSERT INTO word_pairs values (41, 'japonais','chinois');
INSERT INTO word_pairs values (42, 'basket-ball','football');
INSERT INTO word_pairs values (43, 'calin','bisous');
INSERT INTO word_pairs values (44, 'cerise','fraise');
INSERT INTO word_pairs values (45, 'ciel','nuage');
INSERT INTO word_pairs values (46, 'virus','bacterie');
INSERT INTO word_pairs values (47, 'marseille','paris');
INSERT INTO word_pairs values (48, 'parler','chanter');
INSERT INTO word_pairs values (49, 'radioactivite','pollution');
INSERT INTO word_pairs values (50, 'tonnerre','eclair');
INSERT INTO word_pairs values (51, 'seisme','tsunami');
INSERT INTO word_pairs values (52, 'chou','salade');
INSERT INTO word_pairs values (53, 'kung-fu','karate');
INSERT INTO word_pairs values (54, 'yaourt','creme glacee');
INSERT INTO word_pairs values (55, 'deodorant','parfum');
INSERT INTO word_pairs values (56, 'hong-kong','singapour');
INSERT INTO word_pairs values (57, 'chaton','chiot');
INSERT INTO word_pairs values (58, 'bill gates','steve jobs');
INSERT INTO word_pairs values (59, 'carnaval','halloween');
INSERT INTO word_pairs values (60, 'film','histoire');
INSERT INTO word_pairs values (61, 'pikachu','chat');
INSERT INTO word_pairs values (62, 'bain','douche');
INSERT INTO word_pairs values (63, 'vapeur','fumee');
INSERT INTO word_pairs values (64, 'pere noel','jesus');
INSERT INTO word_pairs values (65, 'mer','lac');

