INSERT INTO word_pairs values (25, 'bonheur','amour');
INSERT INTO word_pairs values (26, 'guepe','abeille');
INSERT INTO word_pairs values (27, 'politique','histoire');
INSERT INTO word_pairs values (28, 'tennis','badminton');
INSERT INTO word_pairs values (29, 'gorille','orang-outan');
INSERT INTO word_pairs values (30, 'oeil','camera');
INSERT INTO word_pairs values (31, 'piment','wasabi');
INSERT INTO word_pairs values (32, 'dauphin','baleine');
INSERT INTO word_pairs values (33, 'snapchat','whatsapp');
INSERT INTO word_pairs values (34, 'gel douche','shampooing');
INSERT INTO word_pairs values (35, 'violon','guitare');
INSERT INTO word_pairs values (36, 'rhinoceros','buffle');
INSERT INTO word_pairs values (37, 'fanta','coca cola');
INSERT INTO word_pairs values (38, 'camping','pique-nique');
INSERT INTO word_pairs values (39, 'sac à dos','sac à main');
INSERT INTO word_pairs values (40, 'le seigneur des anneaux','le hobbit');
INSERT INTO word_pairs values (41, 'japonais','chinois');
INSERT INTO word_pairs values (42, 'basket-ball','football');
INSERT INTO word_pairs values (43, 'calin','bisous');
INSERT INTO word_pairs values (44, 'cerise','fraise');
INSERT INTO word_pairs values (45, 'ciel','nuage');
INSERT INTO word_pairs values (46, 'virus','bacterie');
INSERT INTO word_pairs values (47, 'marseille','paris');
INSERT INTO word_pairs values (48, 'parler','chanter');
INSERT INTO word_pairs values (49, 'radioactivite','pollution');
INSERT INTO word_pairs values (50, 'tonnerre','eclair');
INSERT INTO word_pairs values (51, 'seisme','tsunami');
INSERT INTO word_pairs values (52, 'chou','salade');
INSERT INTO word_pairs values (53, 'kung-fu','karate');
INSERT INTO word_pairs values (54, 'yaourt','crème glacée');
INSERT INTO word_pairs values (55, 'déodorant','parfum');
INSERT INTO word_pairs values (56, 'hong-kong','singapour');
INSERT INTO word_pairs values (57, 'chaton','chiot');
INSERT INTO word_pairs values (58, 'bill gates','steve jobs');
INSERT INTO word_pairs values (59, 'carnaval','halloween');
INSERT INTO word_pairs values (60, 'film','histoire');
INSERT INTO word_pairs values (61, 'pikachu','chat');
INSERT INTO word_pairs values (62, 'bain','douche');
INSERT INTO word_pairs values (63, 'vapeur','fumee');
INSERT INTO word_pairs values (64, 'père noel','jesus');
INSERT INTO word_pairs values (65, 'mer','lac');
INSERT INTO word_pairs values (66, 'tablette','ordinateur');
INSERT INTO word_pairs values (67, 'pot','bol');
INSERT INTO word_pairs values (68, 'boussole','compas');
INSERT INTO word_pairs values (69, 'dessin','peinture');
INSERT INTO word_pairs values (71, 'poissonier','boucher');
INSERT INTO word_pairs values (72, 'sauna','hamam');
INSERT INTO word_pairs values (73, 'Espagne','Portugal');
INSERT INTO word_pairs values (74, 'Russie','Etats-Unis');
INSERT INTO word_pairs values (75, 'Lyon','Bordeaux');
INSERT INTO word_pairs values (76, 'vikings','pirates');
INSERT INTO word_pairs values (77, 'grecs','romains');
INSERT INTO word_pairs values (78, 'Disneyland','Parc Astérix');
INSERT INTO word_pairs values (79, 'baseball','volley');
INSERT INTO word_pairs values (80, 'ping-pong','golf');
INSERT INTO word_pairs values (81, 'triathlon','marathon');
INSERT INTO word_pairs values (82, 'chirurgien','dentiste');
INSERT INTO word_pairs values (83, 'gaucher','ambidextre');
INSERT INTO word_pairs values (84, 'champagne','bière');
INSERT INTO word_pairs values (85, 'trompette','violoncel');
INSERT INTO word_pairs values (86, 'piano','orgue');
INSERT INTO word_pairs values (87, 'Les Simpsons','Rick et Morty');
INSERT INTO word_pairs values (88, 'James Bond','Mission Impossible');
